theme: jekyll-theme-slate
title: Lab 6
description: Create lab file on Github, Classes overview, Create and test Book class, Create and test Library class, Add at least two more books to the library, Add ISBN and a delete book method
